replicas: 1

extraContainers: ""

extraInitContainers: ""

extraEnvs: []

envFrom: []

extraVolumeMounts: []

extraVolumes: []

hostAliases: []

annotations: []

labels: []

agent:
  enabled: false

securityContext:
  runAsUser: null

podSecurityContext:
  fsGroup: null
  runAsUser: null

serviceAccount: "default"

terminationGracePeriod: 30

tolerations: []

nodeSelector: {}

affinity: {}

priorityClassName: ""

updateStrategy:
  type: "RollingUpdate"

nameOverride: "eonax"
fullnameOverride: "eonax-registry"

lifecycle: {}
image:
  registry: "docker.io"
  repository: 'package-registry/distribution'
  tag: lite-8.13.0
  imagePullPolicy: IfNotPresent
livenessProbe:
  httpGet:
    path: /
    port: http-registry
  initialDelaySeconds: 30
  failureThreshold: 3
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /
    port: http-registry
  initialDelaySeconds: 30
  failureThreshold: 3
  periodSeconds: 10
  timeoutSeconds: 5

service:
  port: 8080
  nodePort: ""
  type: ClusterIP
  loadBalancerIP: ""
  annotations: {}

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "100m"
    memory: "512Mi"
