---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "dse.fullname" .}}
  labels:
    {{- include "dse.telemetrystorage.labels" . | nindent 4}}
spec:
  {{- if not .Values.telemetrystorage.autoscaling.enabled}}
  replicas: {{.Values.telemetrystorage.replicaCount}}
  {{- end}}
  selector:
    matchLabels:
      {{- include "dse.telemetrystorage.selectorLabels" . | nindent 6}}
  template:
    metadata:
      {{- with .Values.telemetrystorage.podAnnotations}}
      annotations:
        {{- toYaml . | nindent 8}}
      {{- end}}
      labels:
        {{- include "dse.telemetrystorage.selectorLabels" . | nindent 8}}
          {{- with .Values.telemetrystorage.podLabels}}
          {{- toYaml . | nindent 8}}
          {{- end}}
    spec:
      {{- with .Values.imagePullSecrets}}
      imagePullSecrets:
        {{- toYaml . | nindent 8}}
      {{- end}}
      serviceAccountName: {{include "dse.serviceAccountName" .}}
      securityContext:
        {{- toYaml .Values.telemetrystorage.podSecurityContext | nindent 8}}
      initContainers:
        {{- tpl (toYaml .Values.telemetrystorage.initContainers) . | nindent 8}}
      containers:
      - name: {{.Chart.Name}}
        securityContext:
          {{- toYaml .Values.telemetrystorage.securityContext | nindent 12}}
        # either use the specified image, or use the default one
        image: {{.Values.telemetrystorage.image.repository | required ".Values.telemetrystorage.image.repository is required"}}:{{ .Values.telemetrystorage.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{.Values.telemetrystorage.image.pullPolicy}}
        ports:
        {{- range $key,$value := .Values.telemetrystorage.endpoints}}
        - name: {{$key}}
          containerPort: {{$value.port}}
          protocol: TCP
        {{- end}}
        {{- if .Values.telemetrystorage.livenessProbe.enabled}}
        livenessProbe:
          httpGet:
            path: {{.Values.telemetrystorage.endpoints.default.path}}/check/liveness
            port: {{.Values.telemetrystorage.endpoints.default.port}}
          initialDelaySeconds: {{.Values.telemetrystorage.livenessProbe.initialDelaySeconds}}
          periodSeconds: {{.Values.telemetrystorage.livenessProbe.periodSeconds}}
          timeoutSeconds: {{.Values.telemetrystorage.livenessProbe.timeoutSeconds}}
          failureThreshold: {{.Values.telemetrystorage.livenessProbe.failureThreshold}}
          successThreshold: {{.Values.telemetrystorage.livenessProbe.successThreshold}}
        {{- end}}
        {{- if .Values.telemetrystorage.readinessProbe.enabled}}
        readinessProbe:
          httpGet:
            path: {{.Values.telemetrystorage.endpoints.default.path}}/check/readiness
            port: {{.Values.telemetrystorage.endpoints.default.port}}
          initialDelaySeconds: {{.Values.telemetrystorage.readinessProbe.initialDelaySeconds}}
          periodSeconds: {{.Values.telemetrystorage.readinessProbe.periodSeconds}}
          timeoutSeconds: {{.Values.telemetrystorage.readinessProbe.timeoutSeconds}}
          failureThreshold: {{.Values.telemetrystorage.readinessProbe.failureThreshold}}
          successThreshold: {{.Values.telemetrystorage.readinessProbe.successThreshold}}
        {{- end}}
        resources:
          {{- toYaml .Values.telemetrystorage.resources | nindent 12}}
        env:
        - name: "JAVA_TOOL_OPTIONS"
          value: "-Djavax.net.ssl.trustStore={{ .Values.telemetrystorage.vault.hashicorp.cert.tlsPath }}/cacerts -Djavax.net.ssl.trustStorePassword=changeit"


        ##############
        ## HOSTNAME ##
        ##############
        - name: "EDC_HOSTNAME"
          value: {{.Release.Name | quote}}

        ######################
        ## FS CONFIGURATION ##
        ######################
        - name: "EDC_FS_CONFIG"
          value: /app/config.properties

        ######################
        ## ID CONFIGURATION ##
        ######################
        - name: "EDC_PARTICIPANT_ID"
          value: {{.Values.telemetrystorage.did.web.url | required ".Values.telemetrystorage.did.web.url" | quote}}
        - name: "EDC_COMPONENT_ID"
          value: {{include "dse.fullname" .}}

        ##############
        # POSTGRESQL #
        ##############
        - name: "EDC_SQL_SCHEMA_AUTOCREATE"
          value: {{.Values.telemetrystorage.postgresql.schema.autocreate | required ".Values.telemetrystorage.postgresql.schema.autocreate is required" | quote}}

        {{- with .Values.telemetrystorage.postgresql}}
        {{- if .jdbcUrl}}
        - name: "EDC_DATASOURCE_DEFAULT_URL"
          value: {{.jdbcUrl | required ".jdbcUrl is required" | quote}}
        - name: "EDC_DATASOURCE_DEFAULT_USER"
          valueFrom:
            secretKeyRef:
              name: {{.credentials.secret.name | required ".credentials.secret.name is required" | quote}}
              key: {{.credentials.secret.userKey | required ".credentials.secret.userKey is required" | quote}}
        - name: "EDC_DATASOURCE_DEFAULT_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{.credentials.secret.name | required ".credentials.secret.name is required" | quote}}
              key: {{.credentials.secret.passwordKey | required ".credentials.secret.passwordKey is required" | quote}}
        - name: "EDC_DATASOURCE_TELEMETRYEVENT_URL"
          value: {{.jdbcUrl | required ".jdbcUrl is required" | quote}}
        - name: "EDC_DATASOURCE_TELEMETRYEVENT_USER"
          valueFrom:
            secretKeyRef:
              name: {{.credentials.secret.name | required ".credentials.secret.name is required" | quote}}
              key: {{.credentials.secret.userKey | required ".credentials.secret.userKey is required" | quote}}
        - name: "EDC_DATASOURCE_TELEMETRYEVENT_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{.credentials.secret.name | required ".credentials.secret.name is required" | quote}}
              key: {{.credentials.secret.passwordKey | required ".credentials.secret.passwordKey is required" | quote}}
        {{- end}}
        {{- end}}

        #####################
        ## HASHICORP VAULT ##
        #####################
        {{- if .Values.telemetrystorage.vault.hashicorp.url}}
        # https://github.com/eclipse-edc/Connector/tree/main/extensions/common/vault/vault-hashicorp
        - name: "EDC_VAULT_HASHICORP_URL"
          value: {{.Values.telemetrystorage.vault.hashicorp.url | quote}}
        - name: "EDC_VAULT_HASHICORP_TOKEN"
          valueFrom:
            secretKeyRef:
              name: {{.Values.telemetrystorage.vault.hashicorp.token.secret.name | required ".Values.telemetrystorage.vault.hashicorp.token.secret.name is required" | quote}}
              key: {{.Values.telemetrystorage.vault.hashicorp.token.secret.tokenKey | required ".Values.telemetrystorage.vault.hashicorp.token.secret.tokenKey is required" | quote}}
        - name: "EDC_VAULT_HASHICORP_TOKEN_SCHEDULED-RENEW-ENABLED"
          value: {{.Values.telemetrystorage.vault.hashicorp.token.renewal.enabled | quote}}
        - name: "EDC_VAULT_HASHICORP_TOKEN_SCHEDULED_RENEW-BUFFER"
          value: {{ .Values.telemetrystorage.vault.hashicorp.token.renewal.renewBuffer | quote }}
        - name: "EDC_VAULT_HASHICORP_TOKEN_TTL"
          value: {{ .Values.telemetrystorage.vault.hashicorp.token.renewal.ttl | quote }}
        - name: "EDC_VAULT_HASHICORP_TIMEOUT_SECONDS"
          value: {{.Values.telemetrystorage.vault.hashicorp.timeout | quote}}
        - name: "EDC_VAULT_HASHICORP_HEALTH_CHECK_ENABLED"
          value: {{.Values.telemetrystorage.vault.hashicorp.healthCheck.enabled | quote}}
        - name: "EDC_VAULT_HASHICORP_HEALTH_CHECK_STANDBY_OK"
          value: {{.Values.telemetrystorage.vault.hashicorp.healthCheck.standbyOk | quote}}
        - name: "EDC_VAULT_HASHICORP_API_SECRET_PATH"
          value: {{.Values.telemetrystorage.vault.hashicorp.paths.secret | quote}}
        - name: "EDC_VAULT_HASHICORP_FOLDER"
          value: {{ .Values.telemetrystorage.vault.hashicorp.paths.folder | quote }}
        - name: "EDC_VAULT_HASHICORP_API_HEALTH_CHECK_PATH"
          value: {{.Values.telemetrystorage.vault.hashicorp.paths.health | quote}}
        {{- end}}

        #############
        # SSI / DID #
        #############
        - name: "EDC_IAM_ISSUER_ID"
          value: {{.Values.telemetrystorage.did.web.url | required ".Values.telemetrystorage.did.web.url" | quote}}
        - name: "EDC_IDENTITY_DID_URL"
          value: {{.Values.telemetrystorage.did.web.url | required ".Values.telemetrystorage.did.web.url" | quote}}
        - name: "EDC_IAM_DID_WEB_USE_HTTPS"
          value: {{.Values.telemetrystorage.did.web.useHttps | required ".Values.telemetrystorage.did.web.useHttps is required" | quote}}

        #######
        # API #
        #######
        - name: "EDC_WEB_REST_CORS_ENABLED"
          value: {{.Values.telemetrystorage.api.cors.enabled | required ".Values.telemetrystorage.api.cors.enabled is required" | quote}}
        - name: "EDC_WEB_REST_CORS_HEADERS"
          value: {{.Values.telemetrystorage.api.cors.allowedHeaders | required ".Values.telemetrystorage.api.cors.allowedHeaders is required" | quote}}

        {{- range $key, $value := .Values.telemetrystorage.envValueFrom}}
        - name: {{$key | quote}}
          valueFrom:
            {{- tpl (toYaml $value) $ | nindent 16}}
        {{- end}}
        {{- range $key, $value := .Values.telemetrystorage.env}}
        - name: {{$key | quote}}
          value: {{$value | quote}}
        {{- end}}
        {{- if and (or .Values.telemetrystorage.envSecretNames .Values.telemetrystorage.envConfigMapNames) (or (gt (len .Values.telemetrystorage.envSecretNames) 0) (gt (len .Values.telemetrystorage.envConfigMapNames) 0))}}
        envFrom:
        {{- range $value := .Values.telemetrystorage.envSecretNames}}
        - secretRef:
            name: {{$value | quote}}
        {{- end}}
        {{- range $value := .Values.telemetrystorage.envConfigMapNames}}
        - configMapRef:
            name: {{$value | quote}}
        {{- end}}
        {{- end}}
        volumeMounts:
        - name: config
          mountPath: /app/logging.properties
          subPath: logging.properties
        - name: config
          mountPath: /app/opentelemetry.properties
          subPath: opentelemetry.properties
        - name: config
          mountPath: /app/config.properties
          subPath: config.properties
        - name: shared-volume
          readOnly: true
          mountPath: /shared
      volumes:
      - name: config
        configMap:
          name: {{include "dse.fullname" .}}-config
          items:
          - key: logging.properties
            path: logging.properties
          - key: opentelemetry.properties
            path: opentelemetry.properties
          - key: config.properties
            path: config.properties
      - name: shared-volume
        emptyDir: { }
      - name: cert-volume
        secret:
          secretName: {{  required ".Values.telemetrystorage.vault.hashicorp.cert.secretName is required" .Values.telemetrystorage.vault.hashicorp.cert.secretName }}

      {{- with .Values.telemetrystorage.nodeSelector}}
      nodeSelector:
        {{- toYaml . | nindent 8}}
      {{- end}}
      {{- with .Values.telemetrystorage.affinity}}
      affinity:
        {{- toYaml . | nindent 8}}
      {{- end}}
      {{- with .Values.telemetrystorage.tolerations}}
      tolerations:
        {{- toYaml . | nindent 8}}
      {{- end}}