---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dse.fullname" . }}
  labels:
    {{- include "dse.federatedcatalogfilter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.federatedcatalogfilter.autoscaling.enabled }}
  replicas: {{ .Values.federatedcatalogfilter.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dse.federatedcatalogfilter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.federatedcatalogfilter.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dse.federatedcatalogfilter.selectorLabels" . | nindent 8 }}
        {{- with .Values.federatedcatalogfilter.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dse.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.federatedcatalogfilter.podSecurityContext | nindent 8 }}
      initContainers:
        {{- toYaml .Values.federatedcatalogfilter.initContainers | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.federatedcatalogfilter.securityContext | nindent 12 }}

          # either use the specified image, or use the default one
          image: {{ .Values.federatedcatalogfilter.image.repository | required ".Values.federatedcatalogfilter.image.repository is required" }}:{{ .Values.federatedcatalogfilter.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.federatedcatalogfilter.image.pullPolicy }}
          ports:
          {{- range $key,$value := .Values.federatedcatalogfilter.endpoints }}
            - name: {{ $key }}
              containerPort: {{ $value.port }}
              protocol: TCP
          {{- end }}
          {{- if .Values.debug.enabled }}
            - name: debug
              containerPort: {{ .Values.debug.port }}
          {{- end }}
          {{- if .Values.federatedcatalogfilter.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.federatedcatalogfilter.endpoints.default.path }}/check/liveness
              port: {{ .Values.federatedcatalogfilter.endpoints.default.port }}
            initialDelaySeconds: {{ .Values.federatedcatalogfilter.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.federatedcatalogfilter.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.federatedcatalogfilter.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.federatedcatalogfilter.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.federatedcatalogfilter.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.federatedcatalogfilter.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.federatedcatalogfilter.endpoints.default.path }}/check/readiness
              port: {{ .Values.federatedcatalogfilter.endpoints.default.port }}
            initialDelaySeconds: {{ .Values.federatedcatalogfilter.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.federatedcatalogfilter.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.federatedcatalogfilter.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.federatedcatalogfilter.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.federatedcatalogfilter.readinessProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.federatedcatalogfilter.resources | nindent 12 }}
          env:
          - name: "JAVA_TOOL_OPTIONS"
            value: "-Djavax.net.ssl.trustStore={{ .Values.federatedcatalogfilter.vault.hashicorp.cert.tlsPath }}/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
          ######################
          ## FS CONFIGURATION ##
          ######################
          - name: "EDC_FS_CONFIG"
            value: /app/config.properties

          ######################
          ## ID CONFIGURATION ##
          ######################
          - name: "EDC_PARTICIPANT_ID"
            value: {{ .Values.federatedcatalogfilter.did.web.url | required ".Values.federatedcatalogfilter.did.web.url" | quote }}
          - name: "EDC_COMPONENT_ID"
            value: {{ include "dse.fullname" .}}

          {{- with .Values.federatedcatalogfilter.postgresql}}
          {{- if .jdbcUrl}}
          - name: "EDC_DATASOURCE_DEFAULT_URL"
            value: {{.jdbcUrl | required ".jdbcUrl is required" | quote}}
          - name: "EDC_DATASOURCE_DEFAULT_USER"
            valueFrom:
              secretKeyRef:
                name: {{.credentials.secret.name | required ".credentials.secret.name is required" | quote}}
                key: {{.credentials.secret.userKey | required ".credentials.secret.userKey is required" | quote}}
          - name: "EDC_DATASOURCE_DEFAULT_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: {{.credentials.secret.name | required ".credentials.secret.name is required" | quote}}
                key: {{.credentials.secret.passwordKey | required ".credentials.secret.passwordKey is required" | quote}}
          {{- end}}
          {{- end}}
          #####################
          ## HASHICORP VAULT ##
          #####################
          {{- if .Values.federatedcatalogfilter.vault.hashicorp.url }}
          # https://github.com/eclipse-edc/Connector/tree/main/extensions/common/vault/vault-hashicorp
          - name: "EDC_VAULT_HASHICORP_URL"
            value: {{ .Values.federatedcatalogfilter.vault.hashicorp.url | quote }}
          - name: "EDC_VAULT_HASHICORP_TOKEN"
            valueFrom:
              secretKeyRef:
                name: {{.Values.federatedcatalogfilter.vault.hashicorp.token.secret.name | required ".Values.federatedcatalogfilter.vault.hashicorp.token.secret.name is required" | quote}}
                key: {{.Values.federatedcatalogfilter.vault.hashicorp.token.secret.tokenKey | required ".Values.federatedcatalogfilter.vault.hashicorp.token.secret.tokenKey is required" | quote}}
          - name: "EDC_VAULT_HASHICORP_TOKEN_SCHEDULED-RENEW-ENABLED"
            value: {{ .Values.federatedcatalogfilter.vault.hashicorp.token.renewal.enabled | quote }}
          - name: "EDC_VAULT_HASHICORP_TOKEN_RENEW-BUFFER"
            value: {{ .Values.federatedcatalogfilter.vault.hashicorp.token.renewal.renewBuffer | quote }}
          - name: "EDC_VAULT_HASHICORP_TOKEN_TTL"
            value: {{ .Values.federatedcatalogfilter.vault.hashicorp.token.renewal.ttl | quote }}
          - name: "EDC_VAULT_HASHICORP_TIMEOUT_SECONDS"
            value: {{ .Values.federatedcatalogfilter.vault.hashicorp.timeout | quote }}
          - name: "EDC_VAULT_HASHICORP_HEALTH_CHECK_ENABLED"
            value: {{ .Values.federatedcatalogfilter.vault.hashicorp.healthCheck.enabled | quote }}
          - name: "EDC_VAULT_HASHICORP_HEALTH_CHECK_STANDBY_OK"
            value: {{ .Values.federatedcatalogfilter.vault.hashicorp.healthCheck.standbyOk | quote }}
          - name: "EDC_VAULT_HASHICORP_API_SECRET_PATH"
            value: {{ .Values.federatedcatalogfilter.vault.hashicorp.paths.secret | quote }}
          - name: "EDC_VAULT_HASHICORP_FOLDER"
            value: {{.Values.federatedcatalogfilter.vault.hashicorp.paths.folder | quote}}
          - name: "EDC_VAULT_HASHICORP_API_HEALTH_CHECK_PATH"
            value: {{ .Values.federatedcatalogfilter.vault.hashicorp.paths.health | quote }}
          {{- end }}
          #######
          # DID #
          #######
          - name: "EDC_IAM_ISSUER_ID"
            value: {{.Values.federatedcatalogfilter.did.web.url | required ".Values.federatedcatalogfilter.did.web.url" | quote}}
          - name: "EDC_IDENTITY_DID_URL"
            value: {{.Values.federatedcatalogfilter.did.web.url | required ".Values.federatedcatalogfilter.did.web.url" | quote}}
          - name: "EDC_IAM_DID_WEB_USE_HTTPS"
            value: {{.Values.federatedcatalogfilter.did.web.useHttps | required ".Values.federatedcatalogfilter.did.web.useHttps is required" | quote}}
          - name: "DSE_AUTHORITY_DID"
            value: {{.Values.federatedcatalogfilter.trustedIssuers.authority.did | required ".Values.federatedcatalogfilter.trustedIssuers.authority.did is required" | quote}}

          #####################
          # STS REMOTE CONFIG #
          #####################
          - name: "EDC_IAM_STS_OAUTH_TOKEN_URL"
            value: {{.Values.federatedcatalogfilter.sts.tokenUrl | required ".Values.federatedcatalogfilter.sts.tokenUrl is required" | quote}}
          - name: "EDC_IAM_STS_OAUTH_CLIENT_ID"
            value: {{.Values.federatedcatalogfilter.sts.clientId | required ".Values.federatedcatalogfilter.sts.clientId is required" | quote}}
          - name: "EDC_IAM_STS_OAUTH_CLIENT_SECRET_ALIAS"
            value: {{.Values.federatedcatalogfilter.sts.clientSecretAlias | required ".Values.federatedcatalogfilter.sts.clientSecretAlias is required" | quote}}


          #######
          # API #
          #######
          - name: "EDC_WEB_REST_CORS_ENABLED"
            value: {{.Values.federatedcatalogfilter.api.cors.enabled | required ".Values.federatedcatalogfilter.api.cors.enabled is required" | quote}}
          - name: "EDC_WEB_REST_CORS_HEADERS"
            value: {{.Values.federatedcatalogfilter.api.cors.allowedHeaders | required ".Values.federatedcatalogfilter.api.cors.allowedHeaders is required" | quote}}

        {{- range $key, $value := .Values.federatedcatalogfilter.envValueFrom }}
          - name: {{ $key | quote }}
            valueFrom:
              {{- tpl (toYaml $value) $ | nindent 16 }}
        {{- end }}
        {{- range $key, $value := .Values.federatedcatalogfilter.env }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
        {{- end }}
          {{- if and (or .Values.federatedcatalogfilter.envSecretNames .Values.federatedcatalogfilter.envConfigMapNames) (or (gt (len .Values.federatedcatalogfilter.envSecretNames) 0) (gt (len .Values.federatedcatalogfilter.envConfigMapNames) 0)) }}
          envFrom:
          {{- range $value := .Values.federatedcatalogfilter.envSecretNames }}
            - secretRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- range $value := .Values.federatedcatalogfilter.envConfigMapNames }}
            - configMapRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/logging.properties
              subPath: logging.properties
            - name: config
              mountPath: /app/opentelemetry.properties
              subPath: opentelemetry.properties
            - name: config
              mountPath: /app/config.properties
              subPath: config.properties
            - name: shared-volume
              readOnly: true
              mountPath: /shared
      volumes:
        - name: config
          configMap:
            name: {{ include "dse.fullname" . }}-config
            items:
              - key: logging.properties
                path: logging.properties
              - key: opentelemetry.properties
                path: opentelemetry.properties
              - key: config.properties
                path: config.properties
        - name: shared-volume
          emptyDir: { }
        - name: cert-volume
          secret:
            secretName: {{  required ".Values.federatedcatalogfilter.vault.hashicorp.cert.secretName is required" .Values.federatedcatalogfilter.vault.hashicorp.cert.secretName }}

      {{- with .Values.federatedcatalogfilter.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.federatedcatalogfilter.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.federatedcatalogfilter.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}