{{- if .Values.fleetConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fleet.fullname" . }}-config
  labels:
    app: "{{ template "fleet.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- range $path, $config := .Values.fleetConfig }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}
