[metadata]
format.version = "1.1"

[versions]
edc = "0.14.0"
edc-build = "1.1.0"

assertj = "3.27.3"
azureMessagingEventHub = "5.19.2"
awaitility = "4.2.0"
nimbus = "9.45"
jackarta-json = "2.0.1"
jackson = "2.18.2"
rsApi = "4.0.0"
servletApi = "5.0.2"
restAssured = "5.5.0"
httpMockServer = "5.15.0"
jersey = "3.1.10"
jupiter = "5.11.4"
kafka = "3.7.0"
postgres = "42.7.3"
swagger = "2.2.27"
micrometer = "1.14.2"
jjwt = "0.13.0"

[libraries]
edc-spi-core = { module = "org.eclipse.edc:core-spi", version.ref = "edc" }
edc-spi-web = { module = "org.eclipse.edc:web-spi", version.ref = "edc" }
edc-spi-http = { module = "org.eclipse.edc:http-spi", version.ref = "edc" }
edc-spi-policy-engine = { module = "org.eclipse.edc:policy-engine-spi", version.ref = "edc" }
edc-spi-policy-engine-lib = { module = "org.eclipse.edc:policy-engine-lib", version.ref = "edc" }
edc-spi-dpf = { module = "org.eclipse.edc:data-plane-spi", version.ref = "edc" }
edc-spi-participant = { module = "org.eclipse.edc:participant-spi", version.ref = "edc" }
edc-spi-dpf-http = { module = "org.eclipse.edc:data-plane-http-spi", version.ref = "edc" }
edc-spi-contract = { module = "org.eclipse.edc:contract-spi", version.ref = "edc" }
edc-spi-catalog = { module = "org.eclipse.edc:catalog-spi", version.ref = "edc" }
edc-spi-asset = { module = "org.eclipse.edc:asset-spi", version.ref = "edc" }
edc-spi-controlplane = { module = "org.eclipse.edc:control-plane-spi", version.ref = "edc" }
edc-spi-transaction = { module = "org.eclipse.edc:transaction-spi", version.ref = "edc" }
edc-spi-transaction-datasource = { module = "org.eclipse.edc:transaction-datasource-spi", version.ref = "edc" }
edc-spi-identity-did = { module = "org.eclipse.edc:identity-did-spi", version.ref = "edc" }
edc-spi-identitytrust = { module = "org.eclipse.edc:identity-trust-spi", version.ref = "edc" }
edc-spi-jsonld = { module = "org.eclipse.edc:json-ld-spi", version.ref = "edc" }
edc-spi-jwt = { module = "org.eclipse.edc:jwt-spi", version.ref = "edc" }
edc-spi-vc = { module = "org.eclipse.edc:verifiable-credential-spi", version.ref = "edc" }
edc-spi-edrstore = { module = "org.eclipse.edc:edr-store-spi", version.ref = "edc" }
edc-spi-dsp-http = { module = "org.eclipse.edc:dsp-http-spi", version.ref = "edc" }
edc-spi-policy-context = { module = "org.eclipse.edc:request-policy-context-spi", version.ref = "edc" }

edc-core-boot = { module = "org.eclipse.edc:boot", version.ref = "edc" }
edc-core-runtime = { module = "org.eclipse.edc:runtime-core", version.ref = "edc" }
edc-core-connector = { module = "org.eclipse.edc:connector-core", version.ref = "edc" }
edc-core-micrometer = { module = "org.eclipse.edc:micrometer-core", version.ref = "edc" }
edc-core-edr-store = { module = "org.eclipse.edc:edr-store-core", version.ref = "edc" }
edc-core-api = { module = "org.eclipse.edc:api-core", version.ref = "edc" }
edc-core-junit = { module = "org.eclipse.edc:junit", version.ref = "edc" }
edc-core-token = { module = "org.eclipse.edc:token-core", version.ref = "edc" }
edc-core-jersey = { module = "org.eclipse.edc:jersey-core", version.ref = "edc" }
edc-core-sql = { module = "org.eclipse.edc:sql-core", version.ref = "edc" }

edc-transaction-local = { module = "org.eclipse.edc:transaction-local", version.ref = "edc" }
edc-observability-api = { module = "org.eclipse.edc:api-observability", version.ref = "edc" }
edc-configuration-filesystem = { module = "org.eclipse.edc:configuration-filesystem", version.ref = "edc" }
edc-jdklogger = { module = "org.eclipse.edc:monitor-jdk-logger", version.ref = "edc" }
edc-sql-contract-negotiation = { module = "org.eclipse.edc:contract-negotiation-store-sql", version.ref = "edc" }
edc-lib-util = { module = "org.eclipse.edc:util-lib", version.ref = "edc" }
edc-lib-query = { module = "org.eclipse.edc:query-lib", version.ref = "edc" }
edc-lib-store = { module = "org.eclipse.edc:store-lib", version.ref = "edc" }
edc-lib-statemachine = { module = "org.eclipse.edc:state-machine-lib", version.ref = "edc" }
edc-lib-keys = { module = "org.eclipse.edc:keys-lib", version.ref = "edc" }
edc-lib-http = { module = "org.eclipse.edc:http-lib", version.ref = "edc" }
edc-lib-json = { module = "org.eclipse.edc:json-lib", version.ref = "edc" }
edc-lib-token = { module = "org.eclipse.edc:token-lib", version.ref = "edc" }
edc-lib-jsonld = { module = "org.eclipse.edc:json-ld-lib", version.ref = "edc" }
edc-lib-sql = { module = "org.eclipse.edc:sql-lib", version.ref = "edc" }
edc-lib-transform = { module = "org.eclipse.edc:transform-lib", version.ref = "edc" }
edc-lib-crypto-common = { module = "org.eclipse.edc:crypto-common-lib", version.ref = "edc" }
edc-core-policy-monitor = { module = "org.eclipse.edc:policy-monitor-core", version.ref = "edc" }
edc-junit = { module = "org.eclipse.edc:junit", version.ref = "edc" }
edc-http = { module = "org.eclipse.edc:http", version.ref = "edc" }
edc-lib-boot = { module = "org.eclipse.edc:boot-lib", version.ref = "edc" }
edc-runtime-metamodel = { module = "org.eclipse.edc:runtime-metamodel", version.ref = "edc" }
edc-ext-api-management-test-fixtures = { module = "org.eclipse.edc:management-api-test-fixtures", version.ref = "edc" }
edc-ext-control-plane-api-client = { module = "org.eclipse.edc:control-plane-api-client", version.ref = "edc" }
edc-spi-policyengine = { module = "org.eclipse.edc:policy-engine-spi", version.ref = "edc" }
edc-spi-transactionspi = { module = "org.eclipse.edc:transaction-spi", version.ref = "edc" }
edc-ext-vault-hashicorp = { module = "org.eclipse.edc:vault-hashicorp", version.ref = "edc" }
edc-tests-junit-base = { module = "org.eclipse.edc:junit-base", version.ref = "edc" }
edc-api-management-config = { module = "org.eclipse.edc:management-api-configuration", version.ref = "edc" }
edc-api-control-config = { module = "org.eclipse.edc:control-api-configuration", version.ref = "edc" }
edc-api-management = { module = "org.eclipse.edc:management-api", version.ref = "edc" }
edc-dpf-api-public-v2 = { module = "org.eclipse.edc:data-plane-public-api-v2", version.ref = "edc" }
edc-ext-dpf-http = { module = "org.eclipse.edc:data-plane-http", version.ref = "edc" }
edc-ext-dpf-kafka = { module = "org.eclipse.edc:data-plane-kafka", version.ref = "edc" }
edc-ext-dpf-util = { module = "org.eclipse.edc:data-plane-util", version.ref = "edc" }
edc-ext-dpf-core = { module = "org.eclipse.edc:data-plane-core", version.ref = "edc" }
edc-sql-lease = { module = "org.eclipse.edc:sql-lease", version.ref = "edc" }
edc-sql-test-fixtures = { module = "org.eclipse.edc:sql-test-fixtures", version.ref = "edc" }
edc-sql-bootstrapper = { module = "org.eclipse.edc:sql-bootstrapper", version.ref = "edc" }
edc-ext-sql-pool-apache-commons = { module = "org.eclipse.edc:sql-pool-apache-commons", version.ref = "edc" }
edc-spi-boot = { module = "org.eclipse.edc:web-spi", version.ref = "edc" }
edc-ext-sql-edrindex = { module = "org.eclipse.edc:edr-index-sql", version.ref = "edc" }

edc-ext-azure-vault = { module = "org.eclipse.edc.azure:vault-azure", version.ref = "edc" }
edc-identitytrust-core = { module = "org.eclipse.edc:identity-trust-core", version.ref = "edc" }
edc-identitytrust-issuersconfiguration = { module = "org.eclipse.edc:identity-trust-issuers-configuration", version.ref = "edc" }
edc-identity-did-core = { module = "org.eclipse.edc:identity-did-core", version.ref = "edc" }
edc-identity-did-web = { module = "org.eclipse.edc:identity-did-web", version.ref = "edc" }
edc-oauth2-oauth2client = {module = "org.eclipse.edc:oauth2-client", version.ref = "edc" }
edc-sql-jti-store = { module = "org.eclipse.edc:jti-validation-store-sql", version.ref = "edc" }
edc-dsp = { module = "org.eclipse.edc:dsp", version.ref = "edc" }
edc-dsp08-apiconfiguration = { module = "org.eclipse.edc:dsp-http-api-configuration-08", version.ref = "edc" }

# Control Plane
edc-controlplane-api-secrets = { module = "org.eclipse.edc:secrets-api", version.ref = "edc" }
edc-controlplane-bom = { module = "org.eclipse.edc:controlplane-dcp-bom", version.ref = "edc" }
edc-controlplane-sql-bom = { module = "org.eclipse.edc:controlplane-feature-sql-bom", version.ref = "edc" }
edc-controlplane-core = { module = "org.eclipse.edc:control-plane-core", version.ref = "edc" }

# Data Plane
edc-dataplane-bom = { module = "org.eclipse.edc:dataplane-base-bom", version.ref = "edc" }
edc-dataplane-sql-bom = { module = "org.eclipse.edc:dataplane-feature-sql-bom", version.ref = "edc" }

# Identity Hub dependencies
edc-identityhub-spi-participantcontext = { module = "org.eclipse.edc:participant-context-spi", version.ref = "edc" }
edc-identityhub-spi-core = { module = "org.eclipse.edc:identity-hub-spi", version.ref = "edc" }
edc-identityhub-spi-did = { module = "org.eclipse.edc:did-spi", version.ref = "edc" }
edc-identityhub-api-verifiablecredentials = { module = "org.eclipse.edc:verifiable-credentials-api", version.ref = "edc" }
edc-identityhub-bom = { module = "org.eclipse.edc:identityhub-bom", version.ref = "edc" }
edc-identityhub-sql-bom = { module = "org.eclipse.edc:identityhub-feature-sql-bom", version.ref = "edc" }
edc-identityhub-local-statuslist-publisher = { module = "org.eclipse.edc:local-statuslist-publisher", version.ref = "edc" }

# Issuer service
edc-issuerservice-bom = { module = "org.eclipse.edc:issuerservice-bom", version.ref = "edc" }
edc-issuerservice-bom-sql = { module = "org.eclipse.edc:issuerservice-feature-sql-bom", version.ref = "edc" }
edc-issuerservice-spi-holder = { module = "org.eclipse.edc:issuerservice-holder-spi", version.ref = "edc" }
edc-issuerservice-db-attestations = { module = "org.eclipse.edc:issuerservice-database-attestations", version.ref = "edc" }
edc-issuerservice-holder-store-sql = { module = "org.eclipse.edc:issuerservice-holder-store-sql", version.ref = "edc" }
edc-issuerservice-api-credentialdefinition = { module = "org.eclipse.edc:credential-definition-api", version.ref = "edc" }
edc-issuerservice-api-attestation = { module = "org.eclipse.edc:attestation-api", version.ref = "edc" }
edc-issuerservice-api-holder = { module = "org.eclipse.edc:holder-api", version.ref = "edc" }
edc-issuerservice-api-admin-config = { module = "org.eclipse.edc:issuer-admin-api-configuration", version.ref = "edc" }

# Federated Catalotg dependencies
edc-federatedcatalog-spi-core = { module = "org.eclipse.edc:federated-catalog-spi", version.ref = "edc" }
edc-federatedcatalog-bom = { module = "org.eclipse.edc:federatedcatalog-dcp-bom", version.ref = "edc" }

# Other dependencies
micrometer = { module = "io.micrometer:micrometer-core", version.ref = "micrometer" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
restAssured = { module = "io.rest-assured:rest-assured", version.ref = "restAssured" }
jakarta-rsApi = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "rsApi" }
jakartaJson = { module = "org.glassfish:jakarta.json", version.ref = "jackarta-json" }
jetty-jakarta-servletApi = { module = "org.eclipse.jetty.toolchain:jetty-jakarta-servlet-api", version.ref = "servletApi" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-datatypeJsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
nimbus-jwt = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "nimbus" }
mockserver-client = { module = "org.mock-server:mockserver-client-java", version.ref = "httpMockServer" }
mockserver-netty = { module = "org.mock-server:mockserver-netty", version.ref = "httpMockServer" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }
azure-messaging-eventhub = { group = "com.azure", name = "azure-messaging-eventhubs", version.ref = "azureMessagingEventHub" }
jersey-multipart = { module = "org.glassfish.jersey.media:jersey-media-multipart", version.ref = "jersey" }
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }

[bundles]
connector = ["edc-core-boot", "edc-core-connector", "edc-observability-api", "edc-jdklogger",
    "edc-configuration-filesystem", "edc-core-micrometer", "edc-transaction-local", "edc-http", "edc-core-token", "edc-core-runtime"]
coresql = ["edc-core-sql", "edc-sql-lease", "edc-ext-sql-pool-apache-commons", "postgres"]
identity = ["edc-identity-did-core", "edc-identity-did-web"]

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
swagger = { id = "io.swagger.core.v3.swagger-gradle-plugin", version.ref = "swagger" }
edc-build = { id = "org.eclipse.edc.edc-build", version.ref = "edc-build" }