apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dse.fullname" . }}-config
  labels:
    {{- include "dse.labels" . | nindent 4 }}
data:
  logging.properties: |-
    {{- .Values.issuerservice.logging | nindent 4 }}

  opentelemetry.properties: |-
    {{- .Values.issuerservice.opentelemetry | nindent 4 }}

  config.properties: |-
    {{- .Values.issuerservice.config | nindent 4 }}