{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kafka-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-proxy.labels" . | nindent 4 }}
rules:
{{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kafka-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-proxy.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kafka-proxy.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kafka-proxy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}