nameOverride: ""

fullnameOverride: ""

podLabels: [ ]

podAnnotations: [ ]

image:
  registry: "docker.io"
  repository: 'elastic-agent'
  tag: "8.13.0"
  pullPolicy: "IfNotPresent"
  pullSecrets: [ ]

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "100m"
    memory: "512Mi"

serviceAccount: "default"

service:
  enabled: false
  type: ClusterIP
  clusterIP: ""
  loadBalancerIP: ""
  loadBalancerSourceRanges: [ ]
  annotations: { }
  labels: { }

ports:
  http:
    enabled: true
    containerPort: 8220
    servicePort: 8220
    nodePort: ""
    protocol: TCP

fleetConfig:
  elastic-agent.yml: |
    outputs:
      elastic:
        type: elasticsearch
        hosts: '${FLEET_SERVER_ELASTICSEARCH_HOST}'
        protocol: https
        ssl.certificate: "/usr/share/elastic-agent/certs/tls.crt"
        ssl.certificate_authorities: "/usr/share/elastic-agent/certs/ca.crt"
        ssl.key: "/usr/share/elastic-agent/certs/tls.key"
        ssl.verification_mode: "certificate"

    fleet:
      kibana:
        hosts: ['${KIBANA_HOST}']

extraEnvs: [ ]

securityContext:
  runAsUser: null

podSecurityContext:
  fsGroup: null
  runAsUser: null

secretMounts: [ ]

lifecycle: { }

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  failureThreshold: 3
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  failureThreshold: 3
  periodSeconds: 10
  timeoutSeconds: 5

terminationGracePeriod: 30

hostAliases: [ ]

envFrom: [ ]

extraContainers: ""

extraVolumes: [ ]

extraVolumeMounts: [ ]

extraInitContainers: ""

tolerations: [ ]

nodeSelector: { }

affinity: { }

priorityClassName: ""

updateStrategy:
  type: "RollingUpdate"

