---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dse.fullname" . }}
  labels:
    {{- include "dse.telemetryservice.labels" . | nindent 4 }}
spec:
  {{- if not .Values.telemetryservice.autoscaling.enabled }}
  replicas: {{ .Values.telemetryservice.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dse.telemetryservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.telemetryservice.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dse.telemetryservice.selectorLabels" . | nindent 8 }}
        {{- with .Values.telemetryservice.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dse.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.telemetryservice.podSecurityContext | nindent 8 }}
      initContainers:
        {{- toYaml .Values.telemetryservice.initContainers | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.telemetryservice.securityContext | nindent 12 }}
          # either use the specified image, or use the default one
          image: {{ .Values.telemetryservice.image.repository | required ".Values.telemetryservice.image.repository is required" }}:{{ .Values.telemetryservice.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.telemetryservice.image.pullPolicy }}
          ports:
          {{- range $key,$value := .Values.telemetryservice.endpoints }}
            - name: {{ $key }}
              containerPort: {{ $value.port }}
              protocol: TCP
          {{- end }}
          {{- if .Values.telemetryservice.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.telemetryservice.endpoints.default.path }}/check/liveness
              port: {{ .Values.telemetryservice.endpoints.default.port }}
            initialDelaySeconds: {{ .Values.telemetryservice.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.telemetryservice.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.telemetryservice.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.telemetryservice.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.telemetryservice.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.telemetryservice.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.telemetryservice.endpoints.default.path }}/check/readiness
              port: {{ .Values.telemetryservice.endpoints.default.port }}
            initialDelaySeconds: {{ .Values.telemetryservice.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.telemetryservice.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.telemetryservice.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.telemetryservice.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.telemetryservice.readinessProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.telemetryservice.resources | nindent 12 }}
          env:
            - name: "JAVA_TOOL_OPTIONS"
              value: "-Djavax.net.ssl.trustStore={{ .Values.telemetryservice.vault.hashicorp.cert.tlsPath }}/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
              
            ######################
            ## FS CONFIGURATION ##
            ######################
            - name: "EDC_FS_CONFIG"
              value: /app/config.properties

            - name: "EDC_IAM_DID_WEB_USE_HTTPS"
              value: {{ .Values.telemetryservice.did.web.useHttps | required ".Values.telemetryservice.did.web.useHttps is required" | quote }}



            ######################
            ## ID CONFIGURATION ##
            ######################
            - name: "EDC_COMPONENT_ID"
              value: {{ include "dse.fullname" .}}

          ##############
          # POSTGRESQL #
          ##############
            - name: "EDC_SQL_SCHEMA_AUTOCREATE"
              value: {{ .Values.telemetryservice.postgresql.schema.autocreate | required ".Values.telemetryservice.postgresql.schema.autocreate is required" | quote }}

          {{- with .Values.telemetryservice.postgresql }}
          {{- if .jdbcUrl }}
            - name: "EDC_DATASOURCE_DEFAULT_URL"
              value: {{ .jdbcUrl | required ".jdbcUrl is required" | quote }}
            - name: "EDC_DATASOURCE_DEFAULT_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ .credentials.secret.name | required ".credentials.secret.name is required" | quote }}
                  key: {{ .credentials.secret.userKey | required ".credentials.secret.userKey is required" | quote }}
            - name: "EDC_DATASOURCE_DEFAULT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ .credentials.secret.name | required ".credentials.secret.name is required" | quote }}
                  key: {{ .credentials.secret.passwordKey | required ".credentials.secret.passwordKey is required" | quote }}
          {{- end }}
          {{- end }}
            #####################
            ## HASHICORP VAULT ##
            #####################
          {{- if .Values.telemetryservice.vault.hashicorp.url }}
            # https://github.com/eclipse-edc/Connector/tree/main/extensions/common/vault/vault-hashicorp
            - name: "EDC_VAULT_HASHICORP_URL"
              value: {{ .Values.telemetryservice.vault.hashicorp.url | quote }}
            - name: "EDC_VAULT_HASHICORP_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.telemetryservice.vault.hashicorp.token.secret.name | required ".Values.telemetryservice.vault.hashicorp.token.secret.name is required" | quote }}
                  key: {{ .Values.telemetryservice.vault.hashicorp.token.secret.tokenKey | required ".Values.telemetryservice.vault.hashicorp.token.secret.tokenKey is required" | quote }}
            - name: "EDC_VAULT_HASHICORP_TOKEN_SCHEDULED-RENEW-ENABLED"
              value: {{ .Values.telemetryservice.vault.hashicorp.token.renewal.enabled | quote }}
            - name: "EDC_VAULT_HASHICORP_TOKEN_RENEW-BUFFER"
              value: {{ .Values.telemetryservice.vault.hashicorp.token.renewal.renewBuffer | quote }}
            - name: "EDC_VAULT_HASHICORP_TOKEN_TTL"
              value: {{ .Values.telemetryservice.vault.hashicorp.token.renewal.ttl | quote }}
            - name: "EDC_VAULT_HASHICORP_TIMEOUT_SECONDS"
              value: {{ .Values.telemetryservice.vault.hashicorp.timeout | quote }}
            - name: "EDC_VAULT_HASHICORP_HEALTH_CHECK_ENABLED"
              value: {{ .Values.telemetryservice.vault.hashicorp.healthCheck.enabled | quote }}
            - name: "EDC_VAULT_HASHICORP_HEALTH_CHECK_STANDBY_OK"
              value: {{ .Values.telemetryservice.vault.hashicorp.healthCheck.standbyOk | quote }}
            - name: "EDC_VAULT_HASHICORP_API_SECRET_PATH"
              value: {{ .Values.telemetryservice.vault.hashicorp.paths.secret | quote }}
            - name: "EDC_VAULT_HASHICORP_FOLDER"
              value: {{.Values.telemetryservice.vault.hashicorp.paths.folder | quote}}
            - name: "EDC_VAULT_HASHICORP_API_HEALTH_CHECK_PATH"
              value: {{ .Values.telemetryservice.vault.hashicorp.paths.health | quote }}
          {{- end }}

            ############################
            # AZURE CREDENTIAL FACTORY #
            ############################
          {{- if .Values.telemetryservice.credentialfactory.azure.eventhub.sas.uri }}
            - name: "DSE_CREDENTIAL-FACTORY_AZURE_EVENT-HUB_SAS_URI"
              value: {{ .Values.telemetryservice.credentialfactory.azure.eventhub.sas.uri | quote }}
            - name: "DSE_CREDENTIAL-FACTORY_AZURE_EVENT-HUB_SAS_VALIDITY"
              value: {{ .Values.telemetryservice.credentialfactory.azure.eventhub.sas.validity | quote }}
            - name: "DSE_CREDENTIAL-FACTORY_AZURE_EVENT-HUB_SAS_KEY_NAME"
              value: {{ .Values.telemetryservice.credentialfactory.azure.eventhub.sas.key.name | required ".Values.telemetryservice.credentialfactory.azure.eventhub.sas.key.name is required" | quote }}
            - name: "DSE_CREDENTIAL-FACTORY_AZURE_EVENT-HUB_SAS_KEY_ALIAS"
              value: {{ .Values.telemetryservice.credentialfactory.azure.eventhub.sas.key.alias | required ".Values.telemetryservice.credentialfactory.azure.eventhub.sas.key.alias is required" | quote }}
          {{- else }}
            - name: "DSE_CREDENTIAL-FACTORY_AZURE_EVENT-HUB_CONNECTION-STRING_ALIAS"
              value: {{ .Values.telemetryservice.credentialfactory.azure.eventhub.connectionstring.alias | required ".Values.telemetryservice.credentialfactory.azure.eventhub.connectionstring.alias is required" | quote }}
          {{- end }}

            #######
            # API #
            #######
            - name: "EDC_WEB_REST_CORS_ENABLED"
              value: {{ .Values.telemetryservice.api.cors.enabled | required ".Values.telemetryservice.api.cors.enabled is required" | quote }}
            - name: "EDC_WEB_REST_CORS_HEADERS"
              value: {{ .Values.telemetryservice.api.cors.allowedHeaders | required ".Values.telemetryservice.api.cors.allowedHeaders is required" | quote }}

          {{- range $key, $value := .Values.telemetryservice.envValueFrom }}
            - name: {{ $key | quote }}
              valueFrom:
                {{- tpl (toYaml $value) $ | nindent 16 }}
          {{- end }}
          {{- range $key, $value := .Values.telemetryservice.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          {{- if and (or .Values.telemetryservice.envSecretNames .Values.telemetryservice.envConfigMapNames) (or (gt (len .Values.telemetryservice.envSecretNames) 0) (gt (len .Values.telemetryservice.envConfigMapNames) 0)) }}
          envFrom:
          {{- range $value := .Values.telemetryservice.envSecretNames }}
            - secretRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- range $value := .Values.telemetryservice.envConfigMapNames }}
            - configMapRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/logging.properties
              subPath: logging.properties
            - name: config
              mountPath: /app/opentelemetry.properties
              subPath: opentelemetry.properties
            - name: config
              mountPath: /app/config.properties
              subPath: config.properties
            - name: shared-volume
              readOnly: true
              mountPath: /shared
      volumes:
        - name: config
          configMap:
            name: {{ include "dse.fullname" . }}-config
            items:
            - key: logging.properties
              path: logging.properties
            - key: opentelemetry.properties
              path: opentelemetry.properties
            - key: config.properties
              path: config.properties
        - name: shared-volume
          emptyDir: { }
        - name: cert-volume
          secret:
            secretName: {{  required ".Values.telemetryservice.vault.hashicorp.cert.secretName is required" .Values.telemetryservice.vault.hashicorp.cert.secretName }}
      {{- with .Values.telemetryservice.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.telemetryservice.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.telemetryservice.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}