---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dse.fullname" . }}
  labels:
    {{- include "dse.telemetryagent.labels" . | nindent 4 }}
spec:
  {{- if not .Values.telemetryagent.autoscaling.enabled }}
  replicas: {{ .Values.telemetryagent.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dse.telemetryagent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.telemetryagent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dse.telemetryagent.selectorLabels" . | nindent 8 }}
        {{- with .Values.telemetryagent.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dse.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.telemetryagent.podSecurityContext | nindent 8 }}
      initContainers:
        {{- toYaml .Values.telemetryagent.initContainers | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.telemetryagent.securityContext | nindent 12 }}

          # either use the specified image, or use the default one
          image: {{ .Values.telemetryagent.image.repository | required ".Values.telemetryagent.image.repository is required" }}:{{ .Values.telemetryagent.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.telemetryagent.image.pullPolicy }}
          ports:
          {{- range $key,$value := .Values.telemetryagent.endpoints }}
            - name: {{ $key }}
              containerPort: {{ $value.port }}
              protocol: TCP
          {{- end }}
          {{- if .Values.telemetryagent.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.telemetryagent.endpoints.default.path }}/check/liveness
              port: {{ .Values.telemetryagent.endpoints.default.port }}
            initialDelaySeconds: {{ .Values.telemetryagent.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.telemetryagent.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.telemetryagent.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.telemetryagent.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.telemetryagent.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.telemetryagent.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.telemetryagent.endpoints.default.path }}/check/readiness
              port: {{ .Values.telemetryagent.endpoints.default.port }}
            initialDelaySeconds: {{ .Values.telemetryagent.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.telemetryagent.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.telemetryagent.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.telemetryagent.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.telemetryagent.readinessProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.telemetryagent.resources | nindent 12 }}
          env:
            - name: "JAVA_TOOL_OPTIONS"
              value: "-Djavax.net.ssl.trustStore={{ .Values.telemetryagent.vault.hashicorp.cert.tlsPath }}/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
              
            ######################
            ## FS CONFIGURATION ##
            ######################
            - name: "EDC_FS_CONFIG"
              value: /app/config.properties

            ######################
            ## ID CONFIGURATION ##
            ######################
            - name: "EDC_PARTICIPANT_ID"
              value: {{ include "dse.telemetryagent.did.web.url" . }}
            - name: "EDC_COMPONENT_ID"
              value: {{ include "dse.fullname" . }}
            #####################
            ## HASHICORP VAULT ##
            #####################
          {{- if .Values.telemetryagent.vault.hashicorp.url }}
            # https://github.com/eclipse-edc/Connector/tree/main/extensions/common/vault/vault-hashicorp
            - name: "EDC_VAULT_HASHICORP_URL"
              value: {{ .Values.telemetryagent.vault.hashicorp.url | quote }}
            - name: "EDC_VAULT_HASHICORP_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.telemetryagent.vault.hashicorp.token.secret.name | required ".Values.telemetryagent.vault.hashicorp.token.secret.name is required" | quote }}
                  key: {{ .Values.telemetryagent.vault.hashicorp.token.secret.tokenKey | required ".Values.telemetryagent.vault.hashicorp.token.secret.tokenKey is required" | quote }}
            - name: "EDC_VAULT_HASHICORP_TOKEN_SCHEDULED-RENEW-ENABLED"
              value: {{.Values.telemetryagent.vault.hashicorp.token.renewal.enabled | quote}}
            - name: "EDC_VAULT_HASHICORP_TOKEN_TTL"
              value: {{ .Values.telemetryagent.vault.hashicorp.token.renewal.ttl | quote }}
            - name: "EDC_VAULT_HASHICORP_TOKEN_RENEW-BUFFER"
              value: {{ .Values.telemetryagent.vault.hashicorp.token.renewal.renewBuffer | quote }}
            - name: "EDC_VAULT_HASHICORP_TIMEOUT_SECONDS"
              value: {{ .Values.telemetryagent.vault.hashicorp.timeout | quote }}
            - name: "EDC_VAULT_HASHICORP_HEALTH_CHECK_ENABLED"
              value: {{ .Values.telemetryagent.vault.hashicorp.healthCheck.enabled | quote }}
            - name: "EDC_VAULT_HASHICORP_HEALTH_CHECK_STANDBY_OK"
              value: {{ .Values.telemetryagent.vault.hashicorp.healthCheck.standbyOk | quote }}
            - name: "EDC_VAULT_HASHICORP_API_SECRET_PATH"
              value: {{ .Values.telemetryagent.vault.hashicorp.paths.secret | quote }}
            - name: "EDC_VAULT_HASHICORP_FOLDER"
              value: {{.Values.telemetryagent.vault.hashicorp.paths.folder | quote}}
            - name: "EDC_VAULT_HASHICORP_API_HEALTH_CHECK_PATH"
              value: {{ .Values.telemetryagent.vault.hashicorp.paths.health | quote }}
          {{- end }}

          ##############
          # POSTGRESQL #
          ##############
          {{- with .Values.telemetryagent.postgresql }}
          {{- if .jdbcUrl }}
            - name: "EDC_DATASOURCE_DEFAULT_URL"
              value: {{ .jdbcUrl | required ".jdbcUrl is required" | quote }}
            - name: "EDC_DATASOURCE_DEFAULT_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ .credentials.secret.name | required ".credentials.secret.name is required" | quote }}
                  key: {{ .credentials.secret.userKey | required ".credentials.secret.userKey is required" | quote }}
            - name: "EDC_DATASOURCE_DEFAULT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ .credentials.secret.name | required ".credentials.secret.name is required" | quote }}
                  key: {{ .credentials.secret.passwordKey | required ".credentials.secret.passwordKey is required" | quote }}
          {{- end }}
          {{- end }}


            ############################
            # AZURE CREDENTIAL FACTORY #
            ############################
            - name: "DSE_CREDENTIAL-MANAGER_PRIVATE-KEY_ALIAS"
              value: {{ .Values.telemetryagent.credentialmanager.privatekey.alias | required ".Values.telemetryagent.credentialmanager.privatekey.alias is required" | quote }}

            - name: "DSE_AUTHORITY_DID"
              value: {{ .Values.telemetryagent.authority.did | required ".Values.telemetryagent.authority.did is required" | quote }}
            - name: "DSE_TELEMETRY-SERVICE_EVENTHUB_NAME"
              value: {{ .Values.telemetryagent.telemetryservice.eventhub.name | required ".Values.telemetryagent.telemetryservice.eventhub.name is required" | quote }}
            - name: "DSE_TELEMETRY-SERVICE_EVENTHUB_NAMESPACE"
              value: {{ .Values.telemetryagent.telemetryservice.eventhub.namespace | required ".Values.telemetryagent.telemetryservice.eventhub.namespace is required" | quote }}
            

            #############
            # SSI / DID #
            #############
            - name: "EDC_IH_IAM_ID"
              value: {{ include "dse.telemetryagent.did.web.url" . }}
            - name: "EDC_IAM_DID_WEB_USE_HTTPS"
              value: {{ .Values.telemetryagent.did.web.useHttps | required ".Values.telemetryagent.did.web.useHttps is required" | quote }}
            - name: "EDC_IH_IAM_PUBLICKEY_ALIAS"
              value: {{ .Values.telemetryagent.keys.sts.publicKeyVaultAlias | required ".Values.telemetryagent.keys.sts.publicKeyVaultAlias is required" | quote }}

            #######
            # API #
            #######
            - name: "EDC_WEB_REST_CORS_ENABLED"
              value: {{ .Values.telemetryagent.api.cors.enabled | required ".Values.telemetryagent.api.cors.enabled is required" | quote }}
            - name: "EDC_WEB_REST_CORS_HEADERS"
              value: {{ .Values.telemetryagent.api.cors.allowedHeaders | required ".Values.telemetryagent.api.cors.allowedHeaders is required" | quote }}

          {{- range $key, $value := .Values.telemetryagent.envValueFrom }}
            - name: {{ $key | quote }}
              valueFrom:
                {{- tpl (toYaml $value) $ | nindent 16 }}
          {{- end }}
          {{- range $key, $value := .Values.telemetryagent.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          {{- if and (or .Values.telemetryagent.envSecretNames .Values.telemetryagent.envConfigMapNames) (or (gt (len .Values.telemetryagent.envSecretNames) 0) (gt (len .Values.telemetryagent.envConfigMapNames) 0)) }}
          envFrom:
          {{- range $value := .Values.telemetryagent.envSecretNames }}
            - secretRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- range $value := .Values.telemetryagent.envConfigMapNames }}
            - configMapRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/logging.properties
              subPath: logging.properties
            - name: config
              mountPath: /app/opentelemetry.properties
              subPath: opentelemetry.properties
            - name: config
              mountPath: /app/config.properties
              subPath: config.properties
            - name: shared-volume
              readOnly: true
              mountPath: /shared
      volumes:
        - name: config
          configMap:
            name: {{ include "dse.fullname" . }}-config
            items:
            - key: logging.properties
              path: logging.properties
            - key: opentelemetry.properties
              path: opentelemetry.properties
            - key: config.properties
              path: config.properties
        - name: shared-volume
          emptyDir: { }
        - name: cert-volume
          secret:
            secretName: {{  required ".Values.telemetryagent.vault.hashicorp.cert.secretName is required" .Values.telemetryagent.vault.hashicorp.cert.secretName }}
      {{- with .Values.telemetryagent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.telemetryagent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.telemetryagent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}