{{- if .Values.persistence.shared.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kafka-proxy.fullname" . }}-shared
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-proxy.labels" . | nindent 4 }}
  {{- with .Values.persistence.shared.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.shared.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.shared.size }}
  {{- if .Values.persistence.shared.storageClass }}
  storageClassName: {{ .Values.persistence.shared.storageClass }}
  {{- end }}
{{- end }}