apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.service.managementTargetPort }}
      protocol: TCP
      name: management
  selector:
    {{- include "kafka-proxy.selectorLabels" . | nindent 4 }}