apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dse.fullname" . }}-config
  labels:
    {{- include "dse.labels" . | nindent 4 }}
data:

  logging.properties: |-
    {{- .Values.federatedcatalog.logging | nindent 4 }}

  opentelemetry.properties: |-
    {{- .Values.federatedcatalog.opentelemetry | nindent 4 }}

  config.properties: |-
    {{- .Values.federatedcatalog.config | nindent 4 }}