---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dse.fullname" . }}
  labels:
    {{- include "dse.identityhub.labels" . | nindent 4 }}
spec:
  {{- if not .Values.identityhub.autoscaling.enabled }}
  replicas: {{ .Values.identityhub.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dse.identityhub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.identityhub.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dse.identityhub.selectorLabels" . | nindent 8 }}
        {{- with .Values.identityhub.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dse.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.identityhub.podSecurityContext | nindent 8 }}
      initContainers:
        {{- tpl (toYaml .Values.identityhub.initContainers) . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.identityhub.securityContext | nindent 12 }}

          # either use the specified image, or use the default one
          image: {{ .Values.identityhub.image.repository | required ".Values.identityhub.image.repository is required" }}:{{ .Values.identityhub.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.identityhub.image.pullPolicy }}
          ports:
          {{- range $key,$value := .Values.identityhub.endpoints }}
            - name: {{ $key }}
              containerPort: {{ $value.port }}
              protocol: TCP
          {{- end }}
          {{- if .Values.identityhub.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.identityhub.endpoints.default.path }}/check/liveness
              port: {{ .Values.identityhub.endpoints.default.port }}
            initialDelaySeconds: {{ .Values.identityhub.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.identityhub.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.identityhub.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.identityhub.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.identityhub.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.identityhub.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.identityhub.endpoints.default.path }}/check/readiness
              port: {{ .Values.identityhub.endpoints.default.port }}
            initialDelaySeconds: {{ .Values.identityhub.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.identityhub.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.identityhub.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.identityhub.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.identityhub.readinessProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.identityhub.resources | nindent 12 }}
          env:
            - name: "JAVA_TOOL_OPTIONS"
              value: "-Djavax.net.ssl.trustStore={{ .Values.identityhub.vault.hashicorp.cert.tlsPath }}/cacerts -Djavax.net.ssl.trustStorePassword=changeit"

            ######################
            ## FS CONFIGURATION ##
            ######################
            - name: "EDC_FS_CONFIG"
              value: /app/config.properties

            ######################
            ## ID CONFIGURATION ##
            ######################
            - name: "EDC_PARTICIPANT_ID"
              value: {{ include "dse.identityhub.did.web.url" . }}
            - name: "EDC_COMPONENT_ID"
              value: {{ include "dse.fullname" . }}
            #####################
            ## HASHICORP VAULT ##
            #####################
          {{- if .Values.identityhub.vault.hashicorp.url }}
            # https://github.com/eclipse-edc/Connector/tree/main/extensions/common/vault/vault-hashicorp
            - name: "EDC_VAULT_HASHICORP_URL"
              value: {{ .Values.identityhub.vault.hashicorp.url | quote }}
            - name: "EDC_VAULT_HASHICORP_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.identityhub.vault.hashicorp.token.secret.name | required ".Values.identityhub.vault.hashicorp.token.secret.name is required" | quote }}
                  key: {{ .Values.identityhub.vault.hashicorp.token.secret.tokenKey | required ".Values.identityhub.vault.hashicorp.token.secret.tokenKey is required" | quote }}
            - name: "EDC_VAULT_HASHICORP_TOKEN_SCHEDULED-RENEW-ENABLED"
              value: {{ .Values.identityhub.vault.hashicorp.token.renewal.enabled | quote }}
            - name: "EDC_VAULT_HASHICORP_TOKEN_RENEW-BUFFER"
              value: {{ .Values.identityhub.vault.hashicorp.token.renewal.renewBuffer | quote }}
            - name: "EDC_VAULT_HASHICORP_TOKEN_TTL"
              value: {{ .Values.identityhub.vault.hashicorp.token.renewal.ttl | quote }}
            - name: "EDC_VAULT_HASHICORP_TIMEOUT_SECONDS"
              value: {{ .Values.identityhub.vault.hashicorp.timeout | quote }}
            - name: "EDC_VAULT_HASHICORP_HEALTH_CHECK_ENABLED"
              value: {{ .Values.identityhub.vault.hashicorp.healthCheck.enabled | quote }}
            - name: "EDC_VAULT_HASHICORP_HEALTH_CHECK_STANDBY_OK"
              value: {{ .Values.identityhub.vault.hashicorp.healthCheck.standbyOk | quote }}
            - name: "EDC_VAULT_HASHICORP_API_SECRET_PATH"
              value: {{ .Values.identityhub.vault.hashicorp.paths.secret | quote }}
            - name: "EDC_VAULT_HASHICORP_FOLDER"
              value: {{.Values.identityhub.vault.hashicorp.paths.folder | quote}}
            - name: "EDC_VAULT_HASHICORP_API_HEALTH_CHECK_PATH"
              value: {{ .Values.identityhub.vault.hashicorp.paths.health | quote }}
          {{- end }}

            ##############
            # POSTGRESQL #
            ##############
            - name: "EDC_SQL_SCHEMA_AUTOCREATE"
              value: {{.Values.identityhub.postgresql.schema.autocreate | required ".Values.identityhub.postgresql.schema.autocreate is required" | quote}}

          {{- with .Values.identityhub.postgresql }}
          {{- if .jdbcUrl }}
            - name: "EDC_DATASOURCE_DEFAULT_URL"
              value: {{ .jdbcUrl | required ".jdbcUrl is required" | quote }}
            - name: "EDC_DATASOURCE_DEFAULT_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ .credentials.secret.name | required ".credentials.secret.name is required" | quote }}
                  key: {{ .credentials.secret.userKey | required ".credentials.secret.userKey is required" | quote }}
            - name: "EDC_DATASOURCE_DEFAULT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ .credentials.secret.name | required ".credentials.secret.name is required" | quote }}
                  key: {{ .credentials.secret.passwordKey | required ".credentials.secret.passwordKey is required" | quote }}
          {{- end }}
          {{- end }}


          #############
          # SSI / DID #
          #############
            - name: "EDC_IH_IAM_ID"
              value: {{include "dse.identityhub.did.web.url" .}}
            - name: "EDC_IAM_DID_WEB_USE_HTTPS"
              value: {{.Values.identityhub.did.web.useHttps | required ".Values.identityhub.did.web.useHttps is required" | quote}}
            - name: "EDC_IAM_STS_PRIVATEKEY_ALIAS"
              value: {{.Values.identityhub.keys.sts.privateKeyAlias | required ".Values.identityhub.keys.sts.privateKeyAlias is required" | quote}}
            - name: "EDC_IAM_STS_PUBLICKEY_ALIAS"
              value: {{.Values.identityhub.keys.sts.publicKeyAlias | required ".Values.identityhub.keys.sts.publicKeyAlias is required" | quote}}
            - name: "EDC_IAM_STS_PUBLICKEY_ID"
              value: {{.Values.identityhub.keys.sts.publicKeyId | required ".Values.identityhub.keys.sts.publicKeyId is required" | quote}}

          #######
          # API #
          #######
            - name: "EDC_WEB_REST_CORS_ENABLED"
              value: {{ .Values.identityhub.api.cors.enabled | required ".Values.identityhub.api.cors.enabled is required" | quote }}
            - name: "EDC_WEB_REST_CORS_HEADERS"
              value: {{ .Values.identityhub.api.cors.allowedHeaders | required ".Values.identityhub.api.cors.allowedHeaders is required" | quote }}

          ##############
          # SUPERUSER #
          ##############
            - name: "EDC_IH_API_SUPERUSER_SERVICES"
              value: {{.Values.identityhub.participantcontext.superuser.services | required ".Values.identityhub.participantcontext.superuser.services is required" | quote}}

          {{- range $key, $value := .Values.identityhub.envValueFrom }}
            - name: {{ $key | quote }}
              valueFrom:
                {{- tpl (toYaml $value) $ | nindent 16 }}
          {{- end }}
          {{- range $key, $value := .Values.identityhub.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
            {{- if and (or .Values.identityhub.envSecretNames .Values.identityhub.envConfigMapNames) (or (gt (len .Values.identityhub.envSecretNames) 0) (gt (len .Values.identityhub.envConfigMapNames) 0)) }}
          envFrom:
          {{- range $value := .Values.identityhub.envSecretNames }}
            - secretRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- range $value := .Values.identityhub.envConfigMapNames }}
            - configMapRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/logging.properties
              subPath: logging.properties
            - name: config
              mountPath: /app/opentelemetry.properties
              subPath: opentelemetry.properties
            - name: config
              mountPath: /app/config.properties
              subPath: config.properties
            - name: shared-volume
              readOnly: true
              mountPath: /shared
      volumes:
        - name: config
          configMap:
            name: {{ include "dse.fullname" . }}-config
            items:
              - key: logging.properties
                path: logging.properties
              - key: opentelemetry.properties
                path: opentelemetry.properties
              - key: config.properties
                path: config.properties
        - name: shared-volume
          emptyDir: { }
        - name: cert-volume
          secret:
            secretName: {{  required ".Values.identityhub.vault.hashicorp.cert.secretName is required" .Values.identityhub.vault.hashicorp.cert.secretName }}

      {{- with .Values.identityhub.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.identityhub.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.identityhub.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}