---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "dse.fullname" .}}
  labels:
    {{- include "dse.controlplane.labels" . | nindent 4}}
spec:
  {{- if not .Values.controlplane.autoscaling.enabled}}
  replicas: {{.Values.controlplane.replicaCount}}
  {{- end}}
  selector:
    matchLabels:
      {{- include "dse.controlplane.selectorLabels" . | nindent 6}}
  template:
    metadata:
      {{- with .Values.controlplane.podAnnotations}}
      annotations:
        {{- toYaml . | nindent 8}}
      {{- end}}
      labels:
        {{- include "dse.controlplane.selectorLabels" . | nindent 8}}
          {{- with .Values.controlplane.podLabels}}
          {{- toYaml . | nindent 8}}
          {{- end}}
    spec:
      {{- with .Values.imagePullSecrets}}
      imagePullSecrets:
        {{- toYaml . | nindent 8}}
      {{- end}}
      serviceAccountName: {{include "dse.serviceAccountName" .}}
      securityContext:
        {{- toYaml .Values.controlplane.podSecurityContext | nindent 8}}
      initContainers:
        {{- toYaml .Values.controlplane.initContainers | nindent 8}}
      containers:
        - name: {{.Chart.Name}}
          securityContext:
          {{- toYaml .Values.controlplane.securityContext | nindent 12}}
          # either use the specified image, or use the default one
          image: {{.Values.controlplane.image.repository | required ".Values.controlplane.image.repository is required"}}:{{ .Values.controlplane.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{.Values.controlplane.image.pullPolicy}}
          ports:
        {{- range $key,$value := .Values.controlplane.endpoints}}
            - name: {{$key}}
              containerPort: {{$value.port}}
              protocol: TCP
        {{- end}}
        {{- if .Values.controlplane.livenessProbe.enabled}}
          livenessProbe:
            httpGet:
              path: {{.Values.controlplane.endpoints.default.path}}/check/liveness
              port: {{.Values.controlplane.endpoints.default.port}}
            initialDelaySeconds: {{.Values.controlplane.livenessProbe.initialDelaySeconds}}
            periodSeconds: {{.Values.controlplane.livenessProbe.periodSeconds}}
            timeoutSeconds: {{.Values.controlplane.livenessProbe.timeoutSeconds}}
            failureThreshold: {{.Values.controlplane.livenessProbe.failureThreshold}}
            successThreshold: {{.Values.controlplane.livenessProbe.successThreshold}}
        {{- end}}
        {{- if .Values.controlplane.readinessProbe.enabled}}
          readinessProbe:
            httpGet:
              path: {{.Values.controlplane.endpoints.default.path}}/check/readiness
              port: {{.Values.controlplane.endpoints.default.port}}
            initialDelaySeconds: {{.Values.controlplane.readinessProbe.initialDelaySeconds}}
            periodSeconds: {{.Values.controlplane.readinessProbe.periodSeconds}}
            timeoutSeconds: {{.Values.controlplane.readinessProbe.timeoutSeconds}}
            failureThreshold: {{.Values.controlplane.readinessProbe.failureThreshold}}
            successThreshold: {{.Values.controlplane.readinessProbe.successThreshold}}
        {{- end}}
          resources:
          {{- toYaml .Values.controlplane.resources | nindent 12}}
          env:
          - name: "JAVA_TOOL_OPTIONS"
            value: "-Djavax.net.ssl.trustStore={{ .Values.controlplane.vault.hashicorp.cert.tlsPath }}/cacerts -Djavax.net.ssl.trustStorePassword=changeit"

          ######################
          ## FS CONFIGURATION ##
          ######################
          - name: "EDC_FS_CONFIG"
            value: /app/config.properties

          #################
          ## CONTROL URL ##
          #################
          - name: "EDC_CONTROL_ENDPOINT"
            value: {{include "dse.controlplane.url.control" .}}

          ######################
          ## ID CONFIGURATION ##
          ######################
          - name: "EDC_PARTICIPANT_ID"
            value: {{.Values.controlplane.did.web.url | required ".Values.controlplane.did.web.url" | quote}}
          - name: "EDC_COMPONENT_ID"
            value: {{include "dse.fullname" .}}

          #######
          # DSP #
          #######
          - name: "EDC_DSP_CALLBACK_ADDRESS"
            value: {{include "dse.controlplane.url.protocol" .}}

            ##############
            # POSTGRESQL #
            ##############
          - name: "EDC_SQL_SCHEMA_AUTOCREATE"
            value: {{.Values.controlplane.postgresql.schema.autocreate | required ".Values.controlplane.postgresql.schema.autocreate is required" | quote}}

        {{- with .Values.controlplane.postgresql}}
        {{- if .jdbcUrl}}
          - name: "EDC_DATASOURCE_DEFAULT_URL"
            value: {{.jdbcUrl | required ".jdbcUrl is required" | quote}}
          - name: "EDC_DATASOURCE_DEFAULT_USER"
            valueFrom:
              secretKeyRef:
                name: {{.credentials.secret.name | required ".credentials.secret.name is required" | quote}}
                key: {{.credentials.secret.userKey | required ".credentials.secret.userKey is required" | quote}}
          - name: "EDC_DATASOURCE_DEFAULT_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: {{.credentials.secret.name | required ".credentials.secret.name is required" | quote}}
                key: {{.credentials.secret.passwordKey | required ".credentials.secret.passwordKey is required" | quote}}
        {{- end}}
        {{- end}}


          #####################
          ## HASHICORP VAULT ##
          #####################
        {{- if .Values.controlplane.vault.hashicorp.url }}
          # https://github.com/eclipse-edc/Connector/tree/main/extensions/common/vault/vault-hashicorp
          - name: "EDC_VAULT_HASHICORP_URL"
            value: {{ .Values.controlplane.vault.hashicorp.url | quote }}
          - name: "EDC_VAULT_HASHICORP_TOKEN"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.controlplane.vault.hashicorp.token.secret.name | required ".Values.controlplane.vault.hashicorp.token.secret.name is required" | quote }}
                key: {{ .Values.controlplane.vault.hashicorp.token.secret.tokenKey | required ".Values.controlplane.vault.hashicorp.token.secret.tokenKey is required" | quote }}
          - name: "EDC_VAULT_HASHICORP_TOKEN_SCHEDULED-RENEW-ENABLED"
            value: {{ .Values.controlplane.vault.hashicorp.token.renewal.enabled | quote }}
          - name: "EDC_VAULT_HASHICORP_TOKEN_RENEW-BUFFER"
            value: {{ .Values.controlplane.vault.hashicorp.token.renewal.renewBuffer | quote }}
          - name: "EDC_VAULT_HASHICORP_TOKEN_TTL"
            value: {{ .Values.controlplane.vault.hashicorp.token.renewal.ttl | quote }}
          - name: "EDC_VAULT_HASHICORP_TIMEOUT_SECONDS"
            value: {{ .Values.controlplane.vault.hashicorp.timeout | quote }}
          - name: "EDC_VAULT_HASHICORP_HEALTH_CHECK_ENABLED"
            value: {{ .Values.controlplane.vault.hashicorp.healthCheck.enabled | quote }}
          - name: "EDC_VAULT_HASHICORP_HEALTH_CHECK_STANDBY_OK"
            value: {{ .Values.controlplane.vault.hashicorp.healthCheck.standbyOk | quote }}
          - name: "EDC_VAULT_HASHICORP_API_SECRET_PATH"
            value: {{ .Values.controlplane.vault.hashicorp.paths.secret | quote }}
          - name: "EDC_VAULT_HASHICORP_FOLDER"
            value: {{.Values.controlplane.vault.hashicorp.paths.folder | quote}}
          - name: "EDC_VAULT_HASHICORP_API_HEALTH_CHECK_PATH"
            value: {{ .Values.controlplane.vault.hashicorp.paths.health | quote }}
        {{- end }}

          #######
          # DID #
          #######
          - name: "EDC_IAM_ISSUER_ID"
            value: {{.Values.controlplane.did.web.url | required ".Values.controlplane.did.web.url" | quote}}
          - name: "EDC_IDENTITY_DID_URL"
            value: {{.Values.controlplane.did.web.url | required ".Values.controlplane.did.web.url" | quote}}
          - name: "EDC_IAM_DID_WEB_USE_HTTPS"
            value: {{.Values.controlplane.did.web.useHttps | required ".Values.controlplane.did.web.useHttps is required" | quote}}

          #####################
          # STS REMOTE CONFIG #
          #####################
          - name: "EDC_IAM_STS_OAUTH_TOKEN_URL"
            value: {{.Values.controlplane.sts.tokenUrl | required ".Values.controlplane.sts.tokenUrl is required" | quote}}
          - name: "EDC_IAM_STS_OAUTH_CLIENT_ID"
            value: {{.Values.controlplane.sts.clientId | required ".Values.controlplane.sts.clientId is required" | quote}}
          - name: "EDC_IAM_STS_OAUTH_CLIENT_SECRET_ALIAS"
            value: {{.Values.controlplane.sts.clientSecretAlias | required ".Values.controlplane.sts.clientSecretAlias is required" | quote}}

            #######
            # API #
            #######
          - name: "EDC_WEB_REST_CORS_ENABLED"
            value: {{ .Values.controlplane.api.cors.enabled | required ".Values.controlplane.api.cors.enabled is required" | quote }}
          - name: "EDC_WEB_REST_CORS_HEADERS"
            value: {{ .Values.controlplane.api.cors.allowedHeaders | required ".Values.controlplane.api.cors.allowedHeaders is required" | quote }}

        {{- range $key, $value := .Values.controlplane.envValueFrom }}
          - name: {{ $key | quote }}
            valueFrom:
              {{- tpl (toYaml $value) $ | nindent 16 }}
        {{- end }}
        {{- range $key, $value := .Values.controlplane.env }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
        {{- end }}
          {{- if and (or .Values.controlplane.envSecretNames .Values.controlplane.envConfigMapNames) (or (gt (len .Values.controlplane.envSecretNames) 0) (gt (len .Values.controlplane.envConfigMapNames) 0)) }}
          envFrom:
          {{- range $value := .Values.controlplane.envSecretNames }}
            - secretRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- range $value := .Values.controlplane.envConfigMapNames }}
            - configMapRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/logging.properties
              subPath: logging.properties
            - name: config
              mountPath: /app/opentelemetry.properties
              subPath: opentelemetry.properties
            - name: config
              mountPath: /app/config.properties
              subPath: config.properties
            - name: shared-volume
              readOnly: true
              mountPath: /shared
      volumes:
        - name: config
          configMap:
            name: {{ include "dse.fullname" . }}-config
            items:
              - key: logging.properties
                path: logging.properties
              - key: opentelemetry.properties
                path: opentelemetry.properties
              - key: config.properties
                path: config.properties
        - name: shared-volume
          emptyDir: { }
        - name: cert-volume
          secret:
            secretName: {{  required ".Values.controlplane.vault.hashicorp.cert.secretName is required" .Values.controlplane.vault.hashicorp.cert.secretName }}

      {{- with .Values.controlplane.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controlplane.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controlplane.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}