apiVersion: v1
kind: Service
metadata:
  {{- with .Values.controlplane.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "dse.fullname" . }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "dse.labels" . | nindent 4 }}
    {{- with .Values.controlplane.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.controlplane.service.type }}
  ports:
    {{- range $key,$value := .Values.controlplane.endpoints }}
    - name: {{ $key }}
      targetPort: {{ $key }}
      port: {{ $value.port }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "dse.controlplane.selectorLabels" . | nindent 4 }}
